enum Alias {
    Ping = 'ping',
    Sticker = 'Sticker',
    AddMember = 'add-member',
    DemoteMember = 'demote-member',
    GroupRegistration = 'group-registration',
    KickMember = 'kick-member',
    MentionAll = 'mention-all',
    PromoteMember = 'promote-member',
    TiktokDownloader = 'tiktok',
    TiktokAudioDownloader = 'tiktok-audio',
    InstagramDownloader = 'instagram',
    FacebookDownloader = 'facebook',
    ListOfCommands = 'list-of-commands',
    InstagramAudioDownloader = 'instagram-audio',
    SyncFeature = 'sync-feature',
    AntiSecret = 'anti-secret',
    YoutubeDownload = 'youtube-downloader',
    YoutubeAudioDownload = 'youtube-audio-downloader',
    TwitterDownloader = 'twitter-downloader',
    Ai = 'AI',
    AntiBadword = 'anti-badword',
    AddBadword = 'add-badword',
}

export default Alias