enum CommandDescription {
    Ping = 'Cek Bot',
    Sticker = 'Sticker Maker',
    AddMember = 'Tambah Member',
    KickMember = 'Kick Member',
    DemoteMember = 'Demote Admin',
    PromoteMember = 'Promote Member',
    MentionAll = 'Mention Member',
    FacebookVideoDownloader = 'Facebook',
    InstagramDownloader = 'Instagram',
    TiktokAudioDownloader = 'Tiktok Audio',
    TiktokDownloader = 'Tiktok',
    GroupRegistration = 'Registrasi Group (Owner)',
    ListOfCommands = 'List Command',
    InstagramAudioDownloader = 'Instagram Audio',
    SyncFeature = 'Sync Feature',
    AntiSecret = 'Anti rahasia',
    YoutubeDownload = 'Youtube',
    YoutubeAudioDownload = 'Youtube Audio',
    TwitterDownloader = 'Twitter',
    Ai = 'Ai',
    AntiBadword = 'Anti Badword',
    AddBadword = 'Menambahkan Badword',
    ToHd = 'Pembuat Gambar HD',
}

export default CommandDescription