name: Deployment

on:
  push:
    branches:
      - main
env:
  GIT_SSH_COMMAND: ssh -i /home/forge/.ssh/id_rsa_bot -o IdentitiesOnly=yes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          envs: GIT_SSH_COMMAND
          script: |
            cd /home/forge/ajgbot
            git restore .
            yarn install
            yarn build
            pm2 restart 1 --update-env
            pm2 save
